chore: reusable workflow for ci github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,43 +51,42 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-      - name: Gather environment data
-        run: |
-          ${{ matrix.env }}
-          node --version
-          npm --version
-          yarn --version
-
-      - name: Checkout source
-        uses: actions/checkout@v2
-
-      - uses: actions/setup-node@v2
+      - uses: ./.github/workflows/ci-common.yml
         with:
-          node-version: "${{ matrix.node-version }}"
-          cache: "yarn"
-          cache-dependency-path: yarn.lock
+          env: ${{ matrix.env }}
+          node-version: ${{ matrix.node-version }}
+          os: ${{ matrix.os }}
+      # - name: Gather environment data
+      #   run: |
+      #     ${{ matrix.env }}
+      #     node --version
+      #     npm --version
+      #     yarn --version
 
-      # Publish tests won't work if we haven't configured our committer details.
-      - name: Configure Git user
-        run: |
-          git config --global user.name CI
-          git config --global user.email ci@dendron.so
+      # - name: Checkout source
+      #   uses: actions/checkout@v2
 
-      - name: Restore typescript lib cache
-        uses: actions/cache@v2
-        id: ts-cache
-        with:
-          path: |
-            packages/*/lib/*
-          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-22
-          restore-keys: |
-            ${{ runner.os }}-yarn-9
+      # - uses: actions/setup-node@v2
+      #   with:
+      #     node-version: "${{ matrix.node-version }}"
+      #     cache: "yarn"
+      #     cache-dependency-path: yarn.lock
 
-      - name: Sets env vars for publish test
-        run: |
-          echo "TEST_NEXT_TEMPLATE=1" >> $GITHUB_ENV
-          echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
-        if: runner.os == 'Linux'
+      # # Publish tests won't work if we haven't configured our committer details.
+      # - name: Configure Git user
+      #   run: |
+      #     git config --global user.name CI
+      #     git config --global user.email ci@dendron.so
+
+      # - name: Restore typescript lib cache
+      #   uses: actions/cache@v2
+      #   id: ts-cache
+      #   with:
+      #     path: |
+      #       packages/*/lib/*
+      #     key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-22
+      #     restore-keys: |
+      #       ${{ runner.os }}-yarn-9
 
       - name: Bootstrap
         run: yarn bootstrap:bootstrap
@@ -103,72 +102,137 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           echo 'DISPLAY=:99.0' >>$GITHUB_ENV
 
-      - name: Export test-workspace
-        if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
-        working-directory: ./test-workspace
-        run:  ../node_modules/.bin/dendron exportPod --podId dendron.nextjs --config "dest=../packages/nextjs-template/"
+      # - name: Export test-workspace
+      #   if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
+      #   working-directory: ./test-workspace
+      #   run:  ../node_modules/.bin/dendron exportPod --podId dendron.nextjs --config "dest=../packages/nextjs-template/"
 
-      - name: Install Playwright dependencies
-        if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
-        run: npx playwright install --with-deps
+      # - name: Install Playwright dependencies
+      #   if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
+      #   run: npx playwright install --with-deps
 
-      - name: Run Playwright tests
-        if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
-        run: yarn ci:test:template
+      # - name: Run Playwright tests
+      #   if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x'
+      #   run: yarn ci:test:template
 
-      - name: Upload Playwright test results
-        uses: actions/upload-artifact@v3
-        if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x' && (success() || failure())
-        with:
-          name: test-artifact
-          path: ./packages/nextjs-template/test-results/
+      # - name: Upload Playwright test results
+      #   uses: actions/upload-artifact@v3
+      #   if: runner.os == 'Linux' && matrix.suite == 'cli' && matrix.node-version == '14.x' && (success() || failure())
+      #   with:
+      #     name: test-artifact
+      #     path: ./packages/nextjs-template/test-results/
 
       - name: Run tests
         run: yarn ci:test:${{ matrix.suite }}
         timeout-minutes: 30
 
-  test-plugin-web:
-    strategy:
-      # Allow other matrix jobs to continue after one fails, allowing us to
-      # isolate platform-specific issues.
-      fail-fast: false
+  # test-playwright:
+  #     strategy:
+  #     # Allow other matrix jobs to continue after one fails, allowing us to
+  #     # isolate platform-specific issues.
+  #     fail-fast: false
 
-    timeout-minutes: 15
+  #   timeout-minutes: 15
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout source
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Checkout source
+  #       uses: actions/checkout@v2
 
-      - uses: actions/setup-node@v2
-        with:
-          node-version: "16.x"
-          cache: "yarn"
-          cache-dependency-path: yarn.lock
+  #     - uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "16.x"
+  #         cache: "yarn"
+  #         cache-dependency-path: yarn.lock
 
-      - name: Restore typescript lib cache
-        uses: actions/cache@v2
-        id: ts-cache
-        with:
-          path: |
-            packages/*/lib/*
-          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-21
-          restore-keys: |
-            ${{ runner.os }}-yarn-9
+  #     - name: Restore typescript lib cache
+  #       uses: actions/cache@v2
+  #       id: ts-cache
+  #       with:
+  #         path: |
+  #           packages/*/lib/*
+  #         key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-21
+  #         restore-keys: |
+  #           ${{ runner.os }}-yarn-9
 
-      - name: Bootstrap
-        run: yarn bootstrap:bootstrap
-        shell: bash
+  #     - name: Sets env vars for publish test
+  #       run: |
+  #         echo "TEST_NEXT_TEMPLATE=1" >> $GITHUB_ENV
+  #         echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
+  #       # if: runner.os == 'Linux'
 
-      - name: Build
-        run: yarn bootstrap:buildCI
-        shell: bash
+  #     # - name: Bootstrap
+  #     #   run: yarn bootstrap:bootstrap
+  #     #   shell: bash
 
-      - name: Start Xvfb
-        run: |
-          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
-          echo 'DISPLAY=:99.0' >>$GITHUB_ENV
+  #     - name: Build
+  #       run: yarn bootstrap:buildCI
+  #       shell: bash
 
-      - name: Run Plugin-Web tests
-        run: yarn ci:test:plugin-web
+  #     - name: Start Xvfb
+  #       run: |
+  #         Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
+  #         echo 'DISPLAY=:99.0' >>$GITHUB_ENV
+
+  #     - name: Export test-workspace
+  #       working-directory: ./test-workspace
+  #       run:  ../node_modules/.bin/dendron exportPod --podId dendron.nextjs --config "dest=../packages/nextjs-template/"
+
+  #     - name: Install Playwright dependencies
+  #       run: npx playwright install --with-deps
+
+  #     - name: Run Playwright tests
+  #       run: yarn ci:test:template
+
+  #     - name: Upload Playwright test results
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: test-artifact
+  #         path: ./packages/nextjs-template/test-results/
+
+  # test-plugin-web:
+  #   strategy:
+  #     # Allow other matrix jobs to continue after one fails, allowing us to
+  #     # isolate platform-specific issues.
+  #     fail-fast: false
+
+  #   timeout-minutes: 15
+
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - name: Checkout source
+  #       uses: actions/checkout@v2
+
+  #     - uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "16.x"
+  #         cache: "yarn"
+  #         cache-dependency-path: yarn.lock
+
+  #     - name: Restore typescript lib cache
+  #       uses: actions/cache@v2
+  #       id: ts-cache
+  #       with:
+  #         path: |
+  #           packages/*/lib/*
+  #         key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-21
+  #         restore-keys: |
+  #           ${{ runner.os }}-yarn-9
+
+  #     - name: Bootstrap
+  #       run: yarn bootstrap:bootstrap
+  #       shell: bash
+
+  #     # - name: Build
+  #     #   run: yarn bootstrap:buildCI
+  #     #   shell: bash
+
+  #     - name: Start Xvfb
+  #       run: |
+  #         Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
+  #         echo 'DISPLAY=:99.0' >>$GITHUB_ENV
+
+  #     - name: Run Plugin-Web tests
+  #       run: yarn ci:test:plugin-web
